name: moebooru
description: This simple library aim to provide an easy way to work with the Moebooru based image board
version: 1.0.0
repository: https://github.com/shalien/moebooru

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  http: ^1.0.0
  meta: ^1.9.1
  xml: ^6.3.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  sha_env: ^0.0.1
  test: ^1.21.0
